#
# derived from: https://www.mimuw.edu.pl/~erykk/xe-rpis.php
#


pyvenv rpis
source rpis/bin/activate
# each of the next 3 lines might take a while
pip install numpy
pip install matplotlib
pip install jupyter
# after all this you can start by doing
jupyter notebook

# next time you can just call ./run.sh
